# -*- coding: utf-8 -*-
"""BERT Model NLP Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qx7lBl2M0dUU8I_rd26CjqiUpRkx9kz
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from itertools import product


### 1. load data

df = pd.read_csv('/content/Restaurant reviews.csv')
print(df.head())
print(df.columns)

# select review and rating columns
reviews = df[['Review', 'Rating']].copy()
# drop na
reviews = reviews.dropna(subset=["Review", "Rating"])

# change rating column to numeric
reviews['Rating'] = pd.to_numeric(reviews['Rating'], errors='coerce')

# add positive (1)/negative (0) labels
reviews["Sentiment"] = reviews["Rating"].apply(
    lambda x: "positive" if x >= 4 else "negative"
)

print(reviews.head())
print(reviews["Sentiment"].value_counts())


### 2. train/dev/test sets (70/15/15)

X = reviews["Review"]
y = reviews["Sentiment"]

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.30,   # 30% goes to temp (dev + test)
    random_state=19,
    stratify=y
)

X_dev, X_test, y_dev, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,   # split temp evenly → 15% dev, 15% test
    random_state=19,
    stratify=y_temp
)

# check sizes
print("Train:", len(X_train))
print("Dev:", len(X_dev))
print("Test:", len(X_test))

### 3. BERT imports

import torch

from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)


### 4. convert sentiment labels to numbers for BERT

label_map = {
    "negative": 0,
    "positive": 1
}

y_train_num = y_train.map(label_map)
y_dev_num = y_dev.map(label_map)
y_test_num = y_test.map(label_map)


### 5. tokenize the reviews

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=128
)

dev_encodings = tokenizer(
    list(X_dev),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=128
)


### 6. create dataset class for BERT

class RestaurantReviewDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = list(labels)

    def __getitem__(self, idx):
        item = {}

        for key in self.encodings:
            item[key] = torch.tensor(self.encodings[key][idx])

        item["labels"] = torch.tensor(self.labels[idx])

        return item

    def __len__(self):
        return len(self.labels)


train_dataset = RestaurantReviewDataset(train_encodings, y_train_num)
dev_dataset = RestaurantReviewDataset(dev_encodings, y_dev_num)
test_dataset = RestaurantReviewDataset(test_encodings, y_test_num)


### 7. load BERT model

bert_model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)


### 8. define accuracy metric

def compute_metrics(pred):
    labels = pred.label_ids
    predictions = np.argmax(pred.predictions, axis=1)

    acc = accuracy_score(labels, predictions)

    return {
        "accuracy": acc
    }


### 9. train BERT model

training_args = TrainingArguments(
    output_dir="./bert_restaurant_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./bert_logs",
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

trainer = Trainer(
    model=bert_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics
)

trainer.train()


### 10. dev set evaluation

dev_results = trainer.evaluate(dev_dataset)

print("\n BERT DEV RESULTS")
print(dev_results)


### 11. final test evaluation

test_results = trainer.predict(test_dataset)

y_test_pred_num = np.argmax(test_results.predictions, axis=1)

print("\n FINAL BERT MODEL RESULTS")
print("Test Accuracy:", accuracy_score(y_test_num, y_test_pred_num))

print(classification_report(
    y_test_num,
    y_test_pred_num,
    target_names=["negative", "positive"]
))


### 12. confusion matrix

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_num, y_test_pred_num))


### 13. sample predictions

sample_reviews = [
    "The food was amazing and service was great",
    "Terrible experience, I will never come back",
    "It was okay, nothing special"
]

sample_encodings = tokenizer(
    sample_reviews,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors="pt"
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert_model.to(device)

sample_encodings = {
    key: value.to(device)
    for key, value in sample_encodings.items()
}

bert_model.eval()

with torch.no_grad():
    outputs = bert_model(**sample_encodings)
    sample_pred_nums = torch.argmax(outputs.logits, dim=1)

reverse_label_map = {
    0: "negative",
    1: "positive"
}

sample_predictions = [
    reverse_label_map[p.item()]
    for p in sample_pred_nums
]

print("\nSample predictions:")
for review, prediction in zip(sample_reviews, sample_predictions):
    print(review, "->", prediction)
